### ISSUE TITLE
app-icon.rc file not processed in Makefile

### ISSUE THREAD

**Issue by Gravecat** [Gravecat/for-good-or-ill#83]
The app-icon.rc generates the application icon .o file which is linked into the main executable on Windows. In the Eclipse IDE builds, it's compiled like this:

`windres ../src/app-icon.rc -o src/app-icon.o`

The problem here is that I have no idea how to work that into the Makefile in such a way that'll only run on Windows, and will be ignored on non-Windows platforms. Makefiles are a horrendous mystery to me, and I've bumbled my way through far enough to get it mostly working, but this is a stumbling block.

It's not a huge deal as the Eclipse IDE builds work fine, but the Makefile builds produce a binary which lacks an application icon. If anyone knows a solution to this problem, I would be very grateful for the help.

**Comment by tagorereddy** [comment]
Write something like this in MAKEFILE

```
OS := Windows #Windows or Linux
#Other statements
ifeq ($(OS), Windows)
    windres ../src/app-icon.rc -o src/app-icon.o
    #Add app-icon.o to output build command
else
   #Output build command without app-icon.o
endif
```

MAKEFILE can be exclusively run from Windows CLI as
`make all OS=Windows`

**Comment by Gravecat** [comment]
tagorereddy, you are awesome. :) Looks like the Makefile I'm using already has OS detection built in, so I've worked your solution in there and it works great. ^^
